name: PR 검증

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  frontend:
    name: 프론트엔드 검증
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4
      
    - name: Node.js 설정
      uses: actions/setup-node@v4
      with:
        node-version: '24.7.0'
        cache: 'yarn'
        cache-dependency-path: frontend/yarn.lock
        
    - name: 의존성 설치
      run: yarn install --frozen-lockfile
      
    - name: TypeScript 타입 체크
      run: yarn build
      
    - name: ESLint 검사
      run: yarn lint
      
    - name: 테스트 실행
      run: yarn test --run

  backend:
    name: 백엔드 검증
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4
      
    - name: Java 24 설정
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        
    - name: Gradle 캐시 설정
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Gradle 실행 권한 부여
      run: chmod +x gradlew
      
    - name: 테스트 실행
      run: ./gradlew test
      
    - name: 빌드 검증
      run: ./gradlew build -x test

  validation:
    name: 전체 검증 완료
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    
    steps:
    - name: 검증 완료
      run: echo "모든 검증이 성공적으로 완료되었습니다."